local cfg = {
    -- ==Melee==
    [`weapon_dagger`] = {name = [[Antique Cavalry Dagger]], hash = `weapon_dagger`, weapon = [[weapon_dagger]], class = [[Melee]]},
    [`weapon_bat`] = {name = [[Baseball Bat]], hash = `weapon_bat`, weapon = [[weapon_bat]], class = [[Melee]]},
    [`weapon_bottle`] = {name = [[Broken Bottle]], hash = `weapon_bottle`, weapon = [[weapon_bottle]], class = [[Melee]]},
    [`weapon_crowbar`] = {name = [[Crowbar]], hash = `weapon_crowbar`, weapon = [[weapon_crowbar]], class = [[Melee]]},
    [`weapon_unarmed`] = {name = [[Fist]], hash = `weapon_unarmed`, weapon = [[weapon_unarmed]], class = [[Melee]]},
    [`weapon_flashlight`] = {name = [[Flashlight]], hash = `weapon_flashlight`, weapon = [[weapon_flashlight]], class = [[Melee]]},
    [`weapon_golfclub`] = {name = [[Golf Club]], hash = `weapon_golfclub`, weapon = [[weapon_golfclub]], class = [[Melee]]},
    [`weapon_hammer`] = {name = [[Hammer]], hash = `weapon_hammer`, weapon = [[weapon_hammer]], class = [[Melee]]},
    [`weapon_hatchet`] = {name = [[Hatchet]], hash = `weapon_hatchet`, weapon = [[weapon_hatchet]], class = [[Melee]]},
    [`weapon_knuckle`] = {name = [[Brass Knuckles]], hash = `weapon_knuckle`, weapon = [[weapon_knuckle]], class = [[Melee]]},
    [`weapon_knife`] = {name = [[Knife]], hash = `weapon_knife`, weapon = [[weapon_knife]], class = [[Melee]]},
    [`weapon_machete`] = {name = [[Machete]], hash = `weapon_machete`, weapon = [[weapon_machete]], class = [[Melee]]},
    [`weapon_switchblade`] = {name = [[Switchblade]], hash = `weapon_switchblade`, weapon = [[weapon_switchblade]], class = [[Melee]]},
    [`weapon_nightstick`] = {name = [[Nightstick]], hash = `weapon_nightstick`, weapon = [[weapon_nightstick]], class = [[Melee]]},
    [`weapon_wrench`] = {name = [[Pipe Wrench]], hash = `weapon_wrench`, weapon = [[weapon_wrench]], class = [[Melee]]},
    [`weapon_battleaxe`] = {name = [[Battle Axe]], hash = `weapon_battleaxe`, weapon = [[weapon_battleaxe]], class = [[Melee]]},
    [`weapon_poolcue`] = {name = [[Pool Cue]], hash = `weapon_poolcue`, weapon = [[weapon_poolcue]], class = [[Melee]]},
    [`weapon_stone_hatchet`] = {name = [[Stone Hatchet]], hash = `weapon_stone_hatchet`, weapon = [[weapon_stone_hatchet]], class = [[Melee]]},

    -- ==Handguns==
    [`weapon_pistol`] = {name = [[Pistol]], hash = `weapon_pistol`, weapon = [[weapon_pistol]], class = [[Handguns]]},
    [`weapon_pistol_mk2`] = {name = [[Pistol Mk II]], hash = `weapon_pistol_mk2`, weapon = [[weapon_pistol_mk2]], class = [[Handguns]]},
    [`weapon_combatpistol`] = {name = [[Combat Pistol]], hash = `weapon_combatpistol`, weapon = [[weapon_combatpistol]], class = [[Handguns]]},
    [`weapon_appistol`] = {name = [[AP Pistol]], hash = `weapon_appistol`, weapon = [[weapon_appistol]], class = [[Handguns]]},
    [`weapon_stungun`] = {name = [[Stun Gun]], hash = `weapon_stungun`, weapon = [[weapon_stungun]], class = [[Handguns]]},
    [`weapon_pistol50`] = {name = [[Pistol .50]], hash = `weapon_pistol50`, weapon = [[weapon_pistol50]], class = [[Handguns]]},
    [`weapon_snspistol`] = {name = [[SNS Pistol]], hash = `weapon_snspistol`, weapon = [[weapon_snspistol]], class = [[Handguns]]},
    [`weapon_snspistol_mk2`] = {name = [[SNS Pistol Mk II]], hash = `weapon_snspistol_mk2`, weapon = [[weapon_snspistol_mk2]], class = [[Handguns]]},
    [`weapon_heavypistol`] = {name = [[Heavy Pistol]], hash = `weapon_heavypistol`, weapon = [[weapon_heavypistol]], class = [[Handguns]]},
    [`weapon_vintagepistol`] = {name = [[Vintage Pistol]], hash = `weapon_vintagepistol`, weapon = [[weapon_vintagepistol]], class = [[Handguns]]},
    [`weapon_flaregun`] = {name = [[Flare Gun]], hash = `weapon_flaregun`, weapon = [[weapon_flaregun]], class = [[Handguns]]},
    [`weapon_marksmanpistol`] = {name = [[Marksman Pistol]], hash = `weapon_marksmanpistol`, weapon = [[weapon_marksmanpistol]], class = [[Handguns]]},
    [`weapon_revolver`] = {name = [[Heavy Revolver]], hash = `weapon_revolver`, weapon = [[weapon_revolver]], class = [[Handguns]]},
    [`weapon_revolver_mk2`] = {name = [[Heavy Revolver Mk II]], hash = `weapon_revolver_mk2`, weapon = [[weapon_revolver_mk2]], class = [[Handguns]]},
    [`weapon_doubleaction`] = {name = [[Double Action Revolver]], hash = `weapon_doubleaction`, weapon = [[weapon_doubleaction]], class = [[Handguns]]},
    [`weapon_raypistol`] = {name = [[Up-n-Atomizer]], hash = `weapon_raypistol`, weapon = [[weapon_raypistol]], class = [[Handguns]]},
    [`weapon_ceramicpistol`] = {name = [[Ceramic Pistol]], hash = `weapon_ceramicpistol`, weapon = [[weapon_ceramicpistol]], class = [[Handguns]]},
    [`weapon_navyrevolver`] = {name = [[Navy Revolver]], hash = `weapon_navyrevolver`, weapon = [[weapon_navyrevolver]], class = [[Handguns]]},
    [`weapon_gadgetpistol`] = {name = [[Perico Pistol]], hash = `weapon_gadgetpistol`, weapon = [[weapon_gadgetpistol]], class = [[Handguns]]},
    [`weapon_stungun_mp`] = {name = [[Stun Gun (MP)]], hash = `weapon_stungun_mp`, weapon = [[weapon_stungun_mp]], class = [[Handguns]]},

    -- ==Submachine Guns==
    [`weapon_microsmg`] = {name = [[Micro SMG]], hash = `weapon_microsmg`, weapon = [[weapon_microsmg]], class = [[Submachine Guns]]},
    [`weapon_smg`] = {name = [[SMG]], hash = `weapon_smg`, weapon = [[weapon_smg]], class = [[Submachine Guns]]},
    [`weapon_smg_mk2`] = {name = [[SMG Mk II]], hash = `weapon_smg_mk2`, weapon = [[weapon_smg_mk2]], class = [[Submachine Guns]]},
    [`weapon_assaultsmg`] = {name = [[Assault SMG]], hash = `weapon_assaultsmg`, weapon = [[weapon_assaultsmg]], class = [[Submachine Guns]]},
    [`weapon_combatpdw`] = {name = [[Combat PDW]], hash = `weapon_combatpdw`, weapon = [[weapon_combatpdw]], class = [[Submachine Guns]]},
    [`weapon_machinepistol`] = {name = [[Machine Pistol]], hash = `weapon_machinepistol`, weapon = [[weapon_machinepistol]], class = [[Submachine Guns]]},
    [`weapon_minismg`] = {name = [[Mini SMG]], hash = `weapon_minismg`, weapon = [[weapon_minismg]], class = [[Submachine Guns]]},
    [`weapon_raycarbine`] = {name = [[Unholy Hellbringer]], hash = `weapon_raycarbine`, weapon = [[weapon_raycarbine]], class = [[Submachine Guns]]},

    -- ==Shotguns==
    [`weapon_pumpshotgun`] = {name = [[Pump Shotgun]], hash = `weapon_pumpshotgun`, weapon = [[weapon_pumpshotgun]], class = [[Shotguns]]},
    [`weapon_pumpshotgun_mk2`] = {name = [[Pump Shotgun Mk II]], hash = `weapon_pumpshotgun_mk2`, weapon = [[weapon_pumpshotgun_mk2]], class = [[Shotguns]]},
    [`weapon_sawnoffshotgun`] = {name = [[Sawed-Off Shotgun]], hash = `weapon_sawnoffshotgun`, weapon = [[weapon_sawnoffshotgun]], class = [[Shotguns]]},
    [`weapon_assaultshotgun`] = {name = [[Assault Shotgun]], hash = `weapon_assaultshotgun`, weapon = [[weapon_assaultshotgun]], class = [[Shotguns]]},
    [`weapon_bullpupshotgun`] = {name = [[Bullpup Shotgun]], hash = `weapon_bullpupshotgun`, weapon = [[weapon_bullpupshotgun]], class = [[Shotguns]]},
    [`weapon_musket`] = {name = [[Musket]], hash = `weapon_musket`, weapon = [[weapon_musket]], class = [[Shotguns]]},
    [`weapon_heavyshotgun`] = {name = [[Heavy Shotgun]], hash = `weapon_heavyshotgun`, weapon = [[weapon_heavyshotgun]], class = [[Shotguns]]},
    [`weapon_dbshotgun`] = {name = [[Double Barrel Shotgun]], hash = `weapon_dbshotgun`, weapon = [[weapon_dbshotgun]], class = [[Shotguns]]},
    [`weapon_autoshotgun`] = {name = [[Sweeper Shotgun]], hash = `weapon_autoshotgun`, weapon = [[weapon_autoshotgun]], class = [[Shotguns]]},
    [`weapon_combatshotgun`] = {name = [[Combat Shotgun]], hash = `weapon_combatshotgun`, weapon = [[weapon_combatshotgun]], class = [[Shotguns]]},

    -- ==Assault Rifles==
    [`weapon_assaultrifle`] = {name = [[Assault Rifle]], hash = `weapon_assaultrifle`, weapon = [[weapon_assaultrifle]], class = [[Assault Rifles]]},
    [`weapon_assaultrifle_mk2`] = {name = [[Assault Rifle Mk II]], hash = `weapon_assaultrifle_mk2`, weapon = [[weapon_assaultrifle_mk2]], class = [[Assault Rifles]]},
    [`weapon_carbinerifle`] = {name = [[Carbine Rifle]], hash = `weapon_carbinerifle`, weapon = [[weapon_carbinerifle]], class = [[Assault Rifles]]},
    [`weapon_carbinerifle_mk2`] = {name = [[Carbine Rifle Mk II]], hash = `weapon_carbinerifle_mk2`, weapon = [[weapon_carbinerifle_mk2]], class = [[Assault Rifles]]},
    [`weapon_advancedrifle`] = {name = [[Advanced Rifle]], hash = `weapon_advancedrifle`, weapon = [[weapon_advancedrifle]], class = [[Assault Rifles]]},
    [`weapon_specialcarbine`] = {name = [[Special Carbine]], hash = `weapon_specialcarbine`, weapon = [[weapon_specialcarbine]], class = [[Assault Rifles]]},
    [`weapon_specialcarbine_mk2`] = {name = [[Special Carbine Mk II]], hash = `weapon_specialcarbine_mk2`, weapon = [[weapon_specialcarbine_mk2]], class = [[Assault Rifles]]},
    [`weapon_bullpuprifle`] = {name = [[Bullpup Rifle]], hash = `weapon_bullpuprifle`, weapon = [[weapon_bullpuprifle]], class = [[Assault Rifles]]},
    [`weapon_bullpuprifle_mk2`] = {name = [[Bullpup Rifle Mk II]], hash = `weapon_bullpuprifle_mk2`, weapon = [[weapon_bullpuprifle_mk2]], class = [[Assault Rifles]]},
    [`weapon_compactrifle`] = {name = [[Compact Rifle]], hash = `weapon_compactrifle`, weapon = [[weapon_compactrifle]], class = [[Assault Rifles]]},
    [`weapon_militaryrifle`] = {name = [[Military Rifle]], hash = `weapon_militaryrifle`, weapon = [[weapon_militaryrifle]], class = [[Assault Rifles]]},
    [`weapon_heavyrifle`] = {name = [[Heavy Rifle]], hash = `weapon_heavyrifle`, weapon = [[weapon_heavyrifle]], class = [[Assault Rifles]]},

    -- ==Light Machine Guns==
    [`weapon_mg`] = {name = [[MG]], hash = `weapon_mg`, weapon = [[weapon_mg]], class = [[Light Machine Guns]]},
    [`weapon_combatmg`] = {name = [[Combat MG]], hash = `weapon_combatmg`, weapon = [[weapon_combatmg]], class = [[Light Machine Guns]]},
    [`weapon_combatmg_mk2`] = {name = [[Combat MG Mk II]], hash = `weapon_combatmg_mk2`, weapon = [[weapon_combatmg_mk2]], class = [[Light Machine Guns]]},
    [`weapon_gusenberg`] = {name = [[Gusenberg Sweeper]], hash = `weapon_gusenberg`, weapon = [[weapon_gusenberg]], class = [[Light Machine Guns]]},

    -- ==Sniper Rifles==
    [`weapon_sniperrifle`] = {name = [[Sniper Rifle]], hash = `weapon_sniperrifle`, weapon = [[weapon_sniperrifle]], class = [[Sniper Rifles]]},
    [`weapon_heavysniper`] = {name = [[Heavy Sniper]], hash = `weapon_heavysniper`, weapon = [[weapon_heavysniper]], class = [[Sniper Rifles]]},
    [`weapon_heavysniper_mk2`] = {name = [[Heavy Sniper Mk II]], hash = `weapon_heavysniper_mk2`, weapon = [[weapon_heavysniper_mk2]], class = [[Sniper Rifles]]},
    [`weapon_marksmanrifle`] = {name = [[Marksman Rifle]], hash = `weapon_marksmanrifle`, weapon = [[weapon_marksmanrifle]], class = [[Sniper Rifles]]},
    [`weapon_marksmanrifle_mk2`] = {name = [[Marksman Rifle Mk II]], hash = `weapon_marksmanrifle_mk2`, weapon = [[weapon_marksmanrifle_mk2]], class = [[Sniper Rifles]]},

    -- ==Heavy Weapons==
    [`weapon_rpg`] = {name = [[RPG]], hash = `weapon_rpg`, weapon = [[weapon_rpg]], class = [[Heavy Weapons]]},
    [`weapon_grenadelauncher`] = {name = [[Grenade Launcher]], hash = `weapon_grenadelauncher`, weapon = [[weapon_grenadelauncher]], class = [[Heavy Weapons]]},
    [`weapon_grenadelauncher_smoke`] = {name = [[Grenade Launcher Smoke]], hash = `weapon_grenadelauncher_smoke`, weapon = [[weapon_grenadelauncher_smoke]], class = [[Heavy Weapons]]},
    [`weapon_minigun`] = {name = [[Minigun]], hash = `weapon_minigun`, weapon = [[weapon_minigun]], class = [[Heavy Weapons]]},
    [`weapon_firework`] = {name = [[Firework Launcher]], hash = `weapon_firework`, weapon = [[weapon_firework]], class = [[Heavy Weapons]]},
    [`weapon_railgun`] = {name = [[Railgun]], hash = `weapon_railgun`, weapon = [[weapon_railgun]], class = [[Heavy Weapons]]},
    [`weapon_hominglauncher`] = {name = [[Homing Launcher]], hash = `weapon_hominglauncher`, weapon = [[weapon_hominglauncher]], class = [[Heavy Weapons]]},
    [`weapon_compactlauncher`] = {name = [[Compact Grenade Launcher]], hash = `weapon_compactlauncher`, weapon = [[weapon_compactlauncher]], class = [[Heavy Weapons]]},
    [`weapon_rayminigun`] = {name = [[Widowmaker]], hash = `weapon_rayminigun`, weapon = [[weapon_rayminigun]], class = [[Heavy Weapons]]},
    [`weapon_emplauncher`] = {name = [[Compact EMP Launcher]], hash = `weapon_emplauncher`, weapon = [[weapon_emplauncher]], class = [[Heavy Weapons]]},

    -- ==Throwables==
    [`weapon_grenade`] = {name = [[Grenade]], hash = `weapon_grenade`, weapon = [[weapon_grenade]], class = [[Throwables]]},
    [`weapon_bzgas`] = {name = [[BZ Gas]], hash = `weapon_bzgas`, weapon = [[weapon_bzgas]], class = [[Throwables]]},
    [`weapon_molotov`] = {name = [[Molotov Cocktail]], hash = `weapon_molotov`, weapon = [[weapon_molotov]], class = [[Throwables]]},
    [`weapon_stickybomb`] = {name = [[Sticky Bomb]], hash = `weapon_stickybomb`, weapon = [[weapon_stickybomb]], class = [[Throwables]]},
    [`weapon_proxmine`] = {name = [[Proximity Mines]], hash = `weapon_proxmine`, weapon = [[weapon_proxmine]], class = [[Throwables]]},
    [`weapon_snowball`] = {name = [[Snowballs]], hash = `weapon_snowball`, weapon = [[weapon_snowball]], class = [[Throwables]]},
    [`weapon_pipebomb`] = {name = [[Pipe Bombs]], hash = `weapon_pipebomb`, weapon = [[weapon_pipebomb]], class = [[Throwables]]},
    [`weapon_ball`] = {name = [[Baseball]], hash = `weapon_ball`, weapon = [[weapon_ball]], class = [[Throwables]]},
    [`weapon_smokegrenade`] = {name = [[Tear Gas]], hash = `weapon_smokegrenade`, weapon = [[weapon_smokegrenade]], class = [[Throwables]]},
    [`weapon_flare`] = {name = [[Flare]], hash = `weapon_flare`, weapon = [[weapon_flare]], class = [[Throwables]]},

    -- ==Miscellaneous==
    [`weapon_petrolcan`] = {name = [[Jerry Can]], hash = `weapon_petrolcan`, weapon = [[weapon_petrolcan]], class = [[Miscellaneous]]},
    [`gadget_parachute`] = {name = [[Parachute]], hash = `gadget_parachute`, weapon = [[gadget_parachute]], class = [[Miscellaneous]]},
    [`weapon_fireextinguisher`] = {name = [[Fire Extinguisher]], hash = `weapon_fireextinguisher`, weapon = [[weapon_fireextinguisher]], class = [[Miscellaneous]]},
    [`weapon_hazardcan`] = {name = [[Hazardous Jerry Can]], hash = `weapon_hazardcan`, weapon = [[weapon_hazardcan]], class = [[Miscellaneous]]},
    [`weapon_fertilizercan`] = {name = [[Fertilizer Can]], hash = `weapon_fertilizercan`, weapon = [[weapon_fertilizercan]], class = [[Miscellaneous]]},
}

return cfg
